# Generated by Django 5.2.6 on 2025-09-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Personal bio for roommate matching'),
        ),
        migrations.AddField(
            model_name='user',
            name='budget_max',
            field=models.IntegerField(blank=True, help_text='Maximum monthly budget in dollars', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='budget_min',
            field=models.IntegerField(blank=True, help_text='Minimum monthly budget in dollars', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cleanliness_level',
            field=models.IntegerField(default=50, help_text='Cleanliness preference from 0-100'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='guests_preference',
            field=models.CharField(choices=[('rarely', 'Rarely have guests'), ('occasionally', 'Occasionally have guests'), ('frequently', 'Frequently have guests'), ('no_guests', 'No overnight guests')], default='occasionally', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.TextField(blank=True, help_text='Interests and hobbies'),
        ),
        migrations.AddField(
            model_name='user',
            name='lease_duration',
            field=models.CharField(blank=True, choices=[('3_months', '3 months'), ('6_months', '6 months'), ('12_months', '12 months'), ('18_months', '18 months'), ('24_months', '24+ months'), ('flexible', 'Flexible')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='move_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='pets_preference',
            field=models.CharField(choices=[('no_preference', 'No Preference'), ('has_pets', 'I have pets'), ('no_pets', 'No pets'), ('loves_pets', "Love pets but don't have any")], default='no_preference', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='quiet_hours',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='smoking_preference',
            field=models.CharField(choices=[('no_preference', 'No Preference'), ('smoker', 'I smoke'), ('non_smoker', 'Non-smoker only')], default='no_preference', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='social_level',
            field=models.IntegerField(default=50, help_text='Social preference from 0-100'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterModelTable(
            name='user',
            table='auth_user',
        ),
    ]
