# Generated by Django 5.2.6 on 2025-10-07 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_options_user_bio_user_budget_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('registration_incomplete', 'Registration Incomplete'), ('registration_complete', 'Registration Complete'), ('assessment_in_progress', 'Assessment In Progress'), ('assessment_complete', 'Assessment Complete'), ('completed', 'Onboarding Completed')], default='not_started', max_length=30)),
                ('account_created', models.BooleanField(default=False)),
                ('account_created_at', models.DateTimeField(blank=True, null=True)),
                ('personal_info_completed', models.BooleanField(default=False)),
                ('personal_info_completed_at', models.DateTimeField(blank=True, null=True)),
                ('location_preferences_completed', models.BooleanField(default=False)),
                ('location_preferences_completed_at', models.DateTimeField(blank=True, null=True)),
                ('lifestyle_preferences_completed', models.BooleanField(default=False)),
                ('lifestyle_preferences_completed_at', models.DateTimeField(blank=True, null=True)),
                ('assessment_started', models.BooleanField(default=False)),
                ('assessment_started_at', models.DateTimeField(blank=True, null=True)),
                ('assessment_completed', models.BooleanField(default=False)),
                ('assessment_completed_at', models.DateTimeField(blank=True, null=True)),
                ('registration_progress_percentage', models.IntegerField(default=0, help_text='0-100 percentage of registration completion')),
                ('assessment_progress_percentage', models.IntegerField(default=0, help_text='0-100 percentage of assessment completion')),
                ('overall_progress_percentage', models.IntegerField(default=0, help_text='0-100 percentage of overall onboarding completion')),
                ('current_step', models.CharField(default='account_setup', help_text='Current onboarding step', max_length=50)),
                ('total_steps', models.IntegerField(default=6, help_text='Total number of onboarding steps')),
                ('completed_steps', models.IntegerField(default=0, help_text='Number of completed steps')),
                ('profile_complete', models.BooleanField(default=False)),
                ('profile_completeness_score', models.IntegerField(default=0, help_text='Profile completeness score 0-100')),
                ('onboarding_started_at', models.DateTimeField(auto_now_add=True)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Onboarding Progress',
                'verbose_name_plural': 'Onboarding Progress Records',
                'ordering': ['-onboarding_started_at'],
            },
        ),
    ]
