# Generated by Django 5.2.6 on 2025-09-20 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coliving', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LivingSpaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload space photos', upload_to='living_spaces/')),
                ('image_type', models.CharField(choices=[('exterior', 'Exterior'), ('living_room', 'Living Room'), ('kitchen', 'Kitchen'), ('bathroom', 'Bathroom'), ('bedroom', 'Bedroom'), ('amenity', 'Amenity'), ('other', 'Other')], default='other', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Main photo for this space')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='LivingSpaceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.IntegerField(help_text='Overall rating (1-5)')),
                ('cleanliness_rating', models.IntegerField(help_text='Cleanliness rating (1-5)')),
                ('location_rating', models.IntegerField(help_text='Location rating (1-5)')),
                ('value_rating', models.IntegerField(help_text='Value for money (1-5)')),
                ('roommate_compatibility', models.IntegerField(help_text='Roommate compatibility (1-5)')),
                ('review_text', models.TextField(help_text='Detailed review')),
                ('pros', models.TextField(blank=True, help_text='What you liked')),
                ('cons', models.TextField(blank=True, help_text='What could be improved')),
                ('verified_stay', models.BooleanField(default=False, help_text='Reviewer actually lived here')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Room name or number', max_length=100)),
                ('room_type', models.CharField(choices=[('bedroom', 'Bedroom'), ('shared_bedroom', 'Shared Bedroom'), ('studio', 'Studio'), ('master_bedroom', 'Master Bedroom')], default='bedroom', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('size_sqft', models.IntegerField(blank=True, help_text='Room size in square feet', null=True)),
                ('has_private_bathroom', models.BooleanField(default=False)),
                ('has_balcony', models.BooleanField(default=False)),
                ('has_closet', models.BooleanField(default=True)),
                ('furnished', models.BooleanField(default=False)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('security_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Why do you want to live here?')),
                ('move_in_date', models.DateField()),
                ('lease_duration_months', models.IntegerField(help_text='Desired lease duration in months')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('review_message', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='livingspace',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livingspace',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='livingspace',
            name='country',
            field=models.CharField(default='United States', max_length=50),
        ),
        migrations.AddField(
            model_name='livingspace',
            name='description',
            field=models.TextField(blank=True, help_text='Describe your living space'),
        ),
        migrations.AddField(
            model_name='livingspace',
            name='furnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livingspace',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Allow others to discover this space'),
        ),
        migrations.AddField(
            model_name='livingspace',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='livingspace',
            name='lease_duration_months',
            field=models.IntegerField(blank=True, help_text='Lease duration in months', null=True),
        ),
        migrations.AddField(
            model_name='livingspace',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='livingspace',
            name='parking_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livingspace',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='livingspace',
            name='total_bathrooms',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='livingspace',
            name='total_bedrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='livingspace',
            name='total_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='livingspace',
            name='utilities_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livingspace',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name='livingspace',
            index=models.Index(fields=['city', 'is_public'], name='coliving_li_city_0cbbc4_idx'),
        ),
        migrations.AddIndex(
            model_name='livingspace',
            index=models.Index(fields=['available_from'], name='coliving_li_availab_1dbeb1_idx'),
        ),
        migrations.AddField(
            model_name='livingspaceimage',
            name='living_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='coliving.livingspace'),
        ),
        migrations.AddField(
            model_name='livingspaceimage',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_space_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livingspacereview',
            name='living_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='coliving.livingspace'),
        ),
        migrations.AddField(
            model_name='livingspacereview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='current_occupant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupied_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='living_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='coliving.livingspace'),
        ),
        migrations.AddField(
            model_name='livingspaceimage',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='coliving.room'),
        ),
        migrations.AddField(
            model_name='roomapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roomapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roomapplication',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='coliving.room'),
        ),
        migrations.AddIndex(
            model_name='livingspacereview',
            index=models.Index(fields=['living_space', 'overall_rating'], name='coliving_li_living__aeae71_idx'),
        ),
        migrations.AddIndex(
            model_name='livingspacereview',
            index=models.Index(fields=['created_at'], name='coliving_li_created_fdcab0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='livingspacereview',
            unique_together={('living_space', 'reviewer')},
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['living_space', 'is_available'], name='coliving_ro_living__e726cd_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['available_from'], name='coliving_ro_availab_c15e8e_idx'),
        ),
        migrations.AddIndex(
            model_name='livingspaceimage',
            index=models.Index(fields=['living_space', 'is_primary'], name='coliving_li_living__795bcc_idx'),
        ),
        migrations.AddIndex(
            model_name='livingspaceimage',
            index=models.Index(fields=['room'], name='coliving_li_room_id_f9fd10_idx'),
        ),
        migrations.AddIndex(
            model_name='roomapplication',
            index=models.Index(fields=['room', 'status'], name='coliving_ro_room_id_14e2df_idx'),
        ),
        migrations.AddIndex(
            model_name='roomapplication',
            index=models.Index(fields=['applicant', 'status'], name='coliving_ro_applica_efcf5a_idx'),
        ),
        migrations.AddIndex(
            model_name='roomapplication',
            index=models.Index(fields=['created_at'], name='coliving_ro_created_e77018_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roomapplication',
            unique_together={('room', 'applicant')},
        ),
    ]
