# Generated by Django 5.2.6 on 2025-09-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coliving', '0002_livingspaceimage_livingspacereview_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomapplication',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='roomapplication',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='roomapplication',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('employed', 'Employed'), ('self-employed', 'Self-Employed'), ('student', 'Student'), ('unemployed', 'Unemployed')], max_length=20),
        ),
        migrations.AddField(
            model_name='roomapplication',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='roomapplication',
            name='references',
            field=models.TextField(blank=True, help_text='Previous landlords, employers, or personal references'),
        ),
    ]
