# Generated by Django 5.2.7 on 2025-11-13 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coliving', '0004_alter_expense_paid_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LivingSpaceInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('guest', 'Guest')], default='member', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional message from inviter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(help_text='Invitation expiration date')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL)),
                ('living_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='coliving.livingspace')),
            ],
            options={
                'indexes': [models.Index(fields=['invited_user', 'status'], name='coliving_li_invited_713c25_idx'), models.Index(fields=['living_space', 'status'], name='coliving_li_living__f0f5f0_idx')],
                'unique_together': {('living_space', 'invited_user')},
            },
        ),
    ]
