# Generated by Django 5.2.7 on 2025-10-15 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('trait', models.CharField(choices=[('openness', 'Openness'), ('conscientiousness', 'Conscientiousness'), ('extraversion', 'Extraversion'), ('agreeableness', 'Agreeableness'), ('neuroticism', 'Neuroticism'), ('lifestyle', 'Lifestyle')], max_length=20)),
                ('question_type', models.CharField(choices=[('scale', '1-5 Scale'), ('boolean', 'Yes/No'), ('choice', 'Multiple Choice')], max_length=10)),
                ('reverse_scored', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PersonalityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openness', models.IntegerField(default=50)),
                ('conscientiousness', models.IntegerField(default=50)),
                ('extraversion', models.IntegerField(default=50)),
                ('agreeableness', models.IntegerField(default=50)),
                ('neuroticism', models.IntegerField(default=50)),
                ('cleanliness_level', models.IntegerField(default=50)),
                ('social_level', models.IntegerField(default=50)),
                ('quiet_hours', models.BooleanField(default=False)),
                ('pets_allowed', models.BooleanField(default=False)),
                ('smoking_allowed', models.BooleanField(default=False)),
                ('communication_style', models.CharField(choices=[('direct', 'Direct'), ('diplomatic', 'Diplomatic'), ('casual', 'Casual'), ('formal', 'Formal')], default='diplomatic', max_length=20)),
                ('lifestyle_data', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personality_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personality Profile',
                'verbose_name_plural': 'Personality Profiles',
            },
        ),
        migrations.CreateModel(
            name='AssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_value', models.IntegerField()),
                ('response_boolean', models.BooleanField(blank=True, null=True)),
                ('response_text', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personality.assessmentquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
    ]
