# Generated by Django 5.2.6 on 2025-10-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality', '0002_seed_assessment_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalityprofile',
            name='lifestyle_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
