# Generated by Django 5.2.7 on 2025-11-12 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coliving', '0002_bill_calendarevent_notification_shoppinglist_and_more'),
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_primary_for_user1',
            field=models.BooleanField(default=False, help_text="Is this user1's primary match?"),
        ),
        migrations.AddField(
            model_name='match',
            name='is_primary_for_user2',
            field=models.BooleanField(default=False, help_text="Is this user2's primary match?"),
        ),
        migrations.AddField(
            model_name='match',
            name='living_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match', to='coliving.livingspace'),
        ),
    ]
